export { default as PedalSound } from './Pulse_CleanKick01.wav'
export { default as KickSound } from './Resonate_Kick_Long02.wav'
export { default as SnareSound } from './Resonate_Snare03.wav'
export { default as FloorTomSound } from './Resonate_Tom22.wav'
export { default as LargeTomSound } from './Resonate_Tom23.wav'
export { default as SmallTomSound } from './CarnivalCrown_Tom.wav'
export { default as HiHatSound } from './Resonate_Hat_Closed04.wav'
export { default as CrashSound } from './Ride Stick Mid Hard Dry Session.wav'
export { default as RideSound } from './Crash Dry Session Hard 1.wav'
