export { default as EyeOff } from './Eyeoff.svg'
export { default as EyeOpen } from './Eyeopen.svg'
export { default as Logo } from './Group 41.svg'
export { default as Profile } from './Profile.png'
export { default as Search } from './Search.svg'
export { default as AddFriend } from './addFriend.svg'
export { default as Accept } from './accept.svg'
export { default as Refusal } from './refusal.svg'
export { default as Chat } from './Chat.svg'
export { default as UserClose } from './UserClose.svg'
export { default as Close } from './Close.svg'
export { default as Banner } from './Banner.png'
export { default as UserAdd } from './UserAdd.svg'
export { default as EditPencil } from './EditPencil.svg'
export { default as Plus } from './Plus.svg'
export { default as House } from './House.svg'
export { default as Letters_Logo } from './Letters_Logo.svg'
export { default as WelcomeIllust } from './WelcomeIllust.svg'
export { default as Send } from './Send.svg'
export { default as PlusIcon } from './AddPlus.svg'
export { default as User } from './User.svg'
export { default as Lock } from './Lock.svg'
export { default as Copy } from './Copy.svg'
export { default as Mike } from './Mike.svg'
export { default as MikeOff } from './MikeOff.svg'
export { default as Warning } from './Warning.svg'
export { default as DrumImage } from './DrumImage.png'
export { default as Crash } from './drum/Crash.png'
export { default as FloorTom } from './drum/FloorTom.png'
export { default as LargeTom } from './drum/LargeTom.png'
export { default as HiHat } from './drum/HiHat.png'
export { default as Ride } from './drum/Ride.png'
export { default as SmallTom } from './drum/SmallTom.png'
export { default as Snare } from './drum/Snare.png'
export { default as Kick } from './drum/Kick.png'
export { default as Pedal } from './drum/Pedal.png'
export { More } from './More'
export { Instrument } from './Instrument'
export { Volume } from './Volume'
export { LogOut } from './LogOut'
export { Drum } from './Drum'
export { Guitar } from './Guitar'
export { Piano } from './Piano'
export { Slider } from './Slider'
export { Check } from './Check'

export interface IconProps {
  Fill?: string
  width?: number
  height?: number
  onClick?: () => void
}
