export { default as EyeOff } from './Eyeoff.svg'
export { default as EyeOpen } from './Eyeopen.svg'
export { default as Logo } from './Group 41.svg'
export { default as Profile } from './Profile.png'
export { default as Search } from './Search.svg'
export { default as AddFriend } from './addFriend.svg'
export { default as Accept } from './accept.svg'
export { default as Refusal } from './refusal.svg'
export { default as More } from './More.svg'
export { default as Chat } from './Chat.svg'
export { default as UserClose } from './UserClose.svg'
export { default as Close } from './Close.svg'